### ISSUE TITLE
Support for non-Pi hardware

### ISSUE THREAD

**Issue by villanueval** [carpentriesoffline/carpentriesoffline-installer#33]
With the current supply issues, I wonder if it would be better to decouple the project from being Pi-specific. Almost any old desktop or laptop can be used as a server by installing, for example, Ubuntu Server and there would be little difference after that. 

Likewise, the students can run a custom live Ubuntu/Lubuntu with the software already installed or have the packages ready to be installed in the server.

**Comment by jsteyn** [comment]
Hi @villanueval. The project isn't Pi-specific and the intention has always been to provide alternative options eventually. In my presentations about the project, I did mention, as you did, that any old computer can be used.

The main reason we have been focusing on the Pi is that we can create an image with everything "ready-made" as an image to be written to an SD card for the Pi. However, the scripts for downloading the data to be served from a web server are already not Pi specific.

I would help, though, to have more people involved in the project, which is why I'm looking for volunteers. Our progress is slow because we are all quite busy as you can imagine. If you would like to help or know of someone who would like to help, please join any of our meetings or contact me directly and we can talk about things that need doing.

**Comment by villanueval** [comment]
Ah, that is good to know. I'll try to contribute as best as I can.
